# Generated by Django 4.1.2 on 2023-01-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('supplier_city', models.CharField(max_length=255, verbose_name='Supplier City')),
                ('supplier_address', models.CharField(max_length=255, verbose_name='Supplier Address')),
                ('supplier_phone', models.CharField(max_length=255, verbose_name='Supplier Phone')),
                ('supplier_email', models.EmailField(max_length=255, verbose_name='Supplier Email')),
                ('supplier_manager', models.CharField(max_length=255, verbose_name='Supplier Manager')),
                ('supplier_level', models.CharField(max_length=255, verbose_name='Supplier Level')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Is Delete')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
                'db_table': 'supplier',
                'ordering': ['supplier_name'],
            },
        ),
    ]
